root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -tags dev -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
include_ext = ["go", "yaml"]
exclude_dir = ["bin", "tmp", "github_cache", "docs"]
delay = 1000

[log]
time = false

[misc]
clean_on_exit = true
